name: Run tests
on:
  workflow_call:
    inputs:
      VERSION:
        required: true
        description: 'Version name'
        type: string
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Cache build dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache
            /usr/local/lib
            /usr/local/include
            /tmp/abseil-cpp
            /tmp/protobuf
          key: ${{ runner.os }}-build-deps-v2-${{ hashFiles('**/Makefile') }}
          restore-keys: |
            ${{ runner.os }}-build-deps-v2-
            ${{ runner.os }}-build-deps-
      
      - name: Install system dependencies
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y -qq \
            build-essential \
            pkg-config \
            cmake \
            libssl-dev \
            libgtest-dev \
            lcov \
            ccache
          # Enable ccache for faster rebuilds
          echo "/usr/lib/ccache" >> $GITHUB_PATH
            
      - name: Install Abseil (cached)
        run: |
          if [ ! -d "/usr/local/lib/cmake/absl" ]; then
            echo "Building Abseil..."
            if [ ! -d "/tmp/abseil-cpp" ]; then
              git clone --depth=1 --branch=20240116.2 https://github.com/abseil/abseil-cpp.git /tmp/abseil-cpp
            fi
            cd /tmp/abseil-cpp
            mkdir -p build && cd build
            cmake -DCMAKE_CXX_STANDARD=17 \
                  -DABSL_PROPAGATE_CXX_STD=ON \
                  -DBUILD_SHARED_LIBS=ON \
                  -DCMAKE_BUILD_TYPE=Release \
                  -DCMAKE_CXX_COMPILER_LAUNCHER=ccache \
                  ..
            make -j$(nproc) --silent
            sudo make install --silent
            sudo ldconfig
          else
            echo "Abseil already cached"
          fi
      
      - name: Build protobuf library
        run: |
          git clone https://github.com/protocolbuffers/protobuf.git
          cd protobuf
          git submodule update --init --recursive
          ./autogen.sh
          ./configure
          make
          make check           
          
      - name: Install protobuf library
        run: |
          cd protobuf
          sudo make install
          sudo ldconfig
         
      - name: Setup GoogleTest (optimized)
        run: |
          if [ ! -f "/usr/lib/pkgconfig/gtest.pc" ]; then
            cd /usr/src/gtest
            sudo cmake . --quiet
            sudo make --silent
            sudo cp lib/*.a /usr/lib/ 2>/dev/null || sudo cp *.a /usr/lib/
            # Create pkg-config file for gtest
            sudo mkdir -p /usr/lib/pkgconfig
            cat << EOF | sudo tee /usr/lib/pkgconfig/gtest.pc > /dev/null
          Name: gtest
          Description: GoogleTest
          Version: 1.0
          Libs: -lgtest -lgtest_main -pthread
          Cflags: -I/usr/include
          EOF
          else
            echo "GoogleTest already configured"
          fi
          
      - name: Build and test with coverage
        run: |
          # Clean any stale coverage files
          find . -name "*.gcda" -o -name "*.gcno" -delete 2>/dev/null || true
          # Build and run tests in one step
          make coverage
        
      - name: Upload coverage to Coveralls
        uses: coverallsapp/github-action@v2.3.6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: coverage.info
          flag-name: run-tests
          parallel: false
          
      - name: Archive coverage report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: coverage-report
          path: coverage-report/
          retention-days: 7
