name: Run tests

on:
  workflow_call:
    inputs:
      VERSION:
        required: true
        description: 'Version name'
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          libprotobuf-dev \
          protobuf-compiler \
          pkg-config
    
    - name: Build project
      run: make
    
    - name: Run tests
      run: make test
