name: Run tests

on:
  workflow_call:
    inputs:
      VERSION:
        required: true
        description: 'Version name'
        type: string

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4


      - name: Install dependencies (GoogleTest, protobuf, abseil, build tools)
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            cmake make g++ pkg-config \
            libgtest-dev \
            protobuf-compiler libprotobuf-dev \
            libabsl-dev
          
          # Build and install GoogleTest
          cd /usr/src/gtest
          sudo cmake .
          sudo make
          sudo cp lib/*.a /usr/lib

      - name: Build project
        run: |
          make

      - name: Run tests
        run: |
          make test

