name: Main pipeline workflow

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      name:
        description: 'Version name'
        required: true
        type: string
